name: Analyse automatique de l'application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyse:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le projet
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installer les dépendances
        run: npm install

      - name: Analyse de sécurité (npm audit)
        run: npm audit --audit-level=moderate || true

      - name: Analyse du code (ESLint)
        run: |
          npm install eslint --save-dev
          npx eslint . || true
